<?php

// This file was generated by running "composer dump-env"
// https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-production

// put this to project root directory to stop Symfony looking for .env files
// we use real ENV variables in production

return [
    'APP_ENV' => getenv('APP_ENV'), // must use getenv because mod_php does not pass ENV variables to $_SERVER
];
